name: Workflow - Publish Docker Image

on: 
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image to Docker Hub
      with:
        image: liban/test-webapp
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}